-- ============================================================================
-- Persistent Undo/Redo for the Gantt Chart Schedule (and, since they share
-- the same underlying rows, the Cost Estimate Breakdown tab too).
--
-- Design: whole-project snapshots, not per-action deltas. Every mutating
-- action on estimate_categories/estimate_tasks (and their 3 child tables)
-- writes a full JSON snapshot of the project's own rows into
-- gantt_snapshots after it succeeds. Undo/redo moves projects.
-- gantt_undo_cursor_id backward/forward through that project's own log and
-- reconciles the live rows to exactly match the target snapshot (insert
-- what's missing, delete what shouldn't be there, update what changed).
-- See lib/cost-estimate/undo-redo.ts for the actual restore logic — this
-- migration only adds the storage it needs.
--
-- The `generated always as identity` -> `generated by default as identity`
-- change below is what lets a restore re-insert a row with its *original*
-- id (an explicit id on insert needs `overriding system value`, which
-- `generated always` forbids outright) — without this, a redo of a
-- create/delete would hand out a fresh id, breaking predecessor_task_id
-- links and any other reference to the original row. Every existing insert
-- in the app omits `id` and keeps auto-generating exactly as before; this
-- only adds a capability, it doesn't change default behavior.
--
-- `set generated by default` — no trailing `as identity` here. That
-- clause only belongs on `add generated ... as identity` (attaching
-- identity to a column that doesn't have one yet); a column that's
-- already `generated always as identity` just needs its generation mode
-- flipped, and Postgres rejects `as identity` on that form outright
-- (confirmed directly: "syntax error at or near \"as\"").
--
-- Run this AFTER 0036_project_default_labor_cost_percent.sql.
-- ============================================================================

alter table public.estimate_categories
  alter column id set generated by default;
alter table public.estimate_tasks
  alter column id set generated by default;
alter table public.estimate_task_other_costs
  alter column id set generated by default;
alter table public.estimate_task_material_assignments
  alter column id set generated by default;
alter table public.estimate_task_labor_assignments
  alter column id set generated by default;

create table if not exists public.gantt_snapshots (
  id bigint generated always as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  snapshot jsonb not null,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_gantt_snapshots_project_id
  on public.gantt_snapshots (project_id, id);

alter table public.projects
  add column if not exists gantt_undo_cursor_id bigint
    references public.gantt_snapshots (id) on delete set null;

alter table public.gantt_snapshots enable row level security;

drop policy if exists "Admins can view gantt snapshots" on public.gantt_snapshots;
create policy "Admins can view gantt snapshots" on public.gantt_snapshots
  for select using (public.get_my_role() = 'admin');

drop policy if exists "Admins can create gantt snapshots" on public.gantt_snapshots;
create policy "Admins can create gantt snapshots" on public.gantt_snapshots
  for insert with check (public.get_my_role() = 'admin');

drop policy if exists "Admins can delete gantt snapshots" on public.gantt_snapshots;
create policy "Admins can delete gantt snapshots" on public.gantt_snapshots
  for delete using (public.get_my_role() = 'admin');
